/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringFilter } from "../../util/StringFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { MahasiswaListRelationFilter } from "../../mahasiswa/base/MahasiswaListRelationFilter";
import { MatakuliahListRelationFilter } from "../../matakuliah/base/MatakuliahListRelationFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
@InputType()
class DosenWhereInput {
  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => MahasiswaListRelationFilter,
  })
  @ValidateNested()
  @Type(() => MahasiswaListRelationFilter)
  @IsOptional()
  @Field(() => MahasiswaListRelationFilter, {
    nullable: true,
  })
  mahasiswas?: MahasiswaListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => MatakuliahListRelationFilter,
  })
  @ValidateNested()
  @Type(() => MatakuliahListRelationFilter)
  @IsOptional()
  @Field(() => MatakuliahListRelationFilter, {
    nullable: true,
  })
  matakuliahs?: MatakuliahListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  nama?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  nidn?: StringFilter;
}
export { DosenWhereInput };
