/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { DosenService } from "../dosen.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DosenCreateInput } from "./DosenCreateInput";
import { DosenWhereInput } from "./DosenWhereInput";
import { DosenWhereUniqueInput } from "./DosenWhereUniqueInput";
import { DosenFindManyArgs } from "./DosenFindManyArgs";
import { DosenUpdateInput } from "./DosenUpdateInput";
import { Dosen } from "./Dosen";
import { MahasiswaFindManyArgs } from "../../mahasiswa/base/MahasiswaFindManyArgs";
import { Mahasiswa } from "../../mahasiswa/base/Mahasiswa";
import { MahasiswaWhereUniqueInput } from "../../mahasiswa/base/MahasiswaWhereUniqueInput";
import { MatakuliahFindManyArgs } from "../../matakuliah/base/MatakuliahFindManyArgs";
import { Matakuliah } from "../../matakuliah/base/Matakuliah";
import { MatakuliahWhereUniqueInput } from "../../matakuliah/base/MatakuliahWhereUniqueInput";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class DosenControllerBase {
  constructor(
    protected readonly service: DosenService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Dosen",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Dosen })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(@common.Body() data: DosenCreateInput): Promise<Dosen> {
    return await this.service.create({
      data: data,
      select: {
        createdAt: true,
        id: true,
        nama: true,
        nidn: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Dosen",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [Dosen] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(DosenFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Dosen[]> {
    const args = plainToClass(DosenFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        id: true,
        nama: true,
        nidn: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Dosen",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Dosen })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: DosenWhereUniqueInput
  ): Promise<Dosen | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        id: true,
        nama: true,
        nidn: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Dosen",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Dosen })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: DosenWhereUniqueInput,
    @common.Body() data: DosenUpdateInput
  ): Promise<Dosen | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          nama: true,
          nidn: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "Dosen",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Dosen })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: DosenWhereUniqueInput
  ): Promise<Dosen | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          id: true,
          nama: true,
          nidn: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Mahasiswa",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/mahasiswas")
  @ApiNestedQuery(MahasiswaFindManyArgs)
  async findManyMahasiswas(
    @common.Req() request: Request,
    @common.Param() params: DosenWhereUniqueInput
  ): Promise<Mahasiswa[]> {
    const query = plainToClass(MahasiswaFindManyArgs, request.query);
    const results = await this.service.findMahasiswas(params.id, {
      ...query,
      select: {
        createdAt: true,

        dosenpa: {
          select: {
            id: true,
          },
        },

        id: true,
        nama: true,
        npm: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Dosen",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/mahasiswas")
  async connectMahasiswas(
    @common.Param() params: DosenWhereUniqueInput,
    @common.Body() body: MahasiswaWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      mahasiswas: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Dosen",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/mahasiswas")
  async updateMahasiswas(
    @common.Param() params: DosenWhereUniqueInput,
    @common.Body() body: MahasiswaWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      mahasiswas: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Dosen",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/mahasiswas")
  async disconnectMahasiswas(
    @common.Param() params: DosenWhereUniqueInput,
    @common.Body() body: MahasiswaWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      mahasiswas: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Matakuliah",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/matakuliahs")
  @ApiNestedQuery(MatakuliahFindManyArgs)
  async findManyMatakuliahs(
    @common.Req() request: Request,
    @common.Param() params: DosenWhereUniqueInput
  ): Promise<Matakuliah[]> {
    const query = plainToClass(MatakuliahFindManyArgs, request.query);
    const results = await this.service.findMatakuliahs(params.id, {
      ...query,
      select: {
        createdAt: true,

        dosenpengampu: {
          select: {
            id: true,
          },
        },

        id: true,
        kodemk: true,
        namaMatakuliah: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Dosen",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/matakuliahs")
  async connectMatakuliahs(
    @common.Param() params: DosenWhereUniqueInput,
    @common.Body() body: MatakuliahWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      matakuliahs: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Dosen",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/matakuliahs")
  async updateMatakuliahs(
    @common.Param() params: DosenWhereUniqueInput,
    @common.Body() body: MatakuliahWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      matakuliahs: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Dosen",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/matakuliahs")
  async disconnectMatakuliahs(
    @common.Param() params: DosenWhereUniqueInput,
    @common.Body() body: MatakuliahWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      matakuliahs: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
