/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { MahasiswaService } from "../mahasiswa.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { Public } from "../../decorators/public.decorator";
import { MahasiswaCreateInput } from "./MahasiswaCreateInput";
import { MahasiswaWhereInput } from "./MahasiswaWhereInput";
import { MahasiswaWhereUniqueInput } from "./MahasiswaWhereUniqueInput";
import { MahasiswaFindManyArgs } from "./MahasiswaFindManyArgs";
import { MahasiswaUpdateInput } from "./MahasiswaUpdateInput";
import { Mahasiswa } from "./Mahasiswa";
import { DosenFindManyArgs } from "../../dosen/base/DosenFindManyArgs";
import { Dosen } from "../../dosen/base/Dosen";
import { DosenWhereUniqueInput } from "../../dosen/base/DosenWhereUniqueInput";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class MahasiswaControllerBase {
  constructor(
    protected readonly service: MahasiswaService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Mahasiswa",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Mahasiswa })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(@common.Body() data: MahasiswaCreateInput): Promise<Mahasiswa> {
    return await this.service.create({
      data: data,
      select: {
        createdAt: true,
        id: true,
        namaMahasiswa: true,
        npm: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Mahasiswa",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [Mahasiswa] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(MahasiswaFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Mahasiswa[]> {
    const args = plainToClass(MahasiswaFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        id: true,
        namaMahasiswa: true,
        npm: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Mahasiswa",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Mahasiswa })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: MahasiswaWhereUniqueInput
  ): Promise<Mahasiswa | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        id: true,
        namaMahasiswa: true,
        npm: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Mahasiswa",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Mahasiswa })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: MahasiswaWhereUniqueInput,
    @common.Body() data: MahasiswaUpdateInput
  ): Promise<Mahasiswa | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          namaMahasiswa: true,
          npm: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "Mahasiswa",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Mahasiswa })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: MahasiswaWhereUniqueInput
  ): Promise<Mahasiswa | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          id: true,
          namaMahasiswa: true,
          npm: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @Public()
  @common.Get("/:id/nidnDosen")
  @ApiNestedQuery(DosenFindManyArgs)
  async findManyNidnDosen(
    @common.Req() request: Request,
    @common.Param() params: MahasiswaWhereUniqueInput
  ): Promise<Dosen[]> {
    const query = plainToClass(DosenFindManyArgs, request.query);
    const results = await this.service.findNidnDosen(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        mahasiswa: true,
        namaDosen: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Mahasiswa",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/nidnDosen")
  async connectNidnDosen(
    @common.Param() params: MahasiswaWhereUniqueInput,
    @common.Body() body: DosenWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      nidnDosen: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Mahasiswa",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/nidnDosen")
  async updateNidnDosen(
    @common.Param() params: MahasiswaWhereUniqueInput,
    @common.Body() body: DosenWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      nidnDosen: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Mahasiswa",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/nidnDosen")
  async disconnectNidnDosen(
    @common.Param() params: MahasiswaWhereUniqueInput,
    @common.Body() body: DosenWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      nidnDosen: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
